# Numpy = np

In [1]:
import numpy as np

In [2]:
# Podemos crear un ARRAY de UNA DIMENSIÓN

one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
# Podemos crear tambiíen un ARRAY de DOS DIMENCIONES

two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [4]:
type(two_dimensional_array)

numpy.ndarray

In [5]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [6]:
random_int_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_int_between_50_and_100)

[93 79 73 63 99 95]


In [7]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.05275867 0.85693844 0.67937016 0.86791858 0.13924078 0.54314671]


In [8]:
# Mathematical Operations on NumPy Operands

In [9]:
rand_flo = random_floats_between_0_and_1 + 100.0
print(rand_flo)

[100.05275867 100.85693844 100.67937016 100.86791858 100.13924078
 100.54314671]


In [10]:
rand_int = random_int_between_50_and_100 * 3
print(rand_int)

[279 237 219 189 297 285]


In [11]:
# TASK 1
# Crear un dataset con un atributo y una etiqueta:
# 1. secuencia de integers de 6 a 20 (inclusive) a un array NumPy llamado "feature"
# 2. asignar 15 valores a un array NumPy llamada "label"

In [12]:
# Por ejemplo:
# label = (3)(feature) + 4

In [13]:
feature = np.arange(6, 21)
print(feature)
label = np.random.randint(3, 55, 15)
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[43 16 52 25 49 29  5 52 44 21 25 35 12 44 38]


In [14]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 4) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[28 32 36 40 44 48 52 56 60 64 68 72 76 80 84]


In [15]:
# TASK 2
noise = np.random.random([15] * 4) - 2
print(noise)
label = label + noise
print(label)

[[[[-1.27784072 -1.51220541 -1.56180542 ... -1.47774385 -1.5926654
    -1.07524453]
   [-1.16287812 -1.67294716 -1.61958679 ... -1.1651532  -1.81774128
    -1.25738401]
   [-1.1076402  -1.39330765 -1.60530482 ... -1.23226782 -1.52653171
    -1.71955146]
   ...
   [-1.07486747 -1.80941825 -1.11201029 ... -1.04816668 -1.02670899
    -1.08389403]
   [-1.89676293 -1.11197937 -1.61470164 ... -1.83676069 -1.1565659
    -1.9519812 ]
   [-1.7624791  -1.44143208 -1.97877999 ... -1.22615516 -1.09113193
    -1.39680106]]

  [[-1.56782286 -1.99335392 -1.41966366 ... -1.01852515 -1.64668961
    -1.9386891 ]
   [-1.97038659 -1.39403686 -1.36891465 ... -1.4058803  -1.2341245
    -1.15617088]
   [-1.81722574 -1.34492552 -1.21266989 ... -1.87857479 -1.43700495
    -1.29189661]
   ...
   [-1.13640916 -1.85980995 -1.08680066 ... -1.44957766 -1.30772085
    -1.88161456]
   [-1.63378841 -1.55696433 -1.12705842 ... -1.36122255 -1.97400812
    -1.56207301]
   [-1.35105742 -1.82996068 -1.17265178 ... -1.36827

---


# Pandas = pd

In [16]:
import numpy as np
import pandas as pd

In [17]:
# Creamos y poblamos un array NumPy de 5x2.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Creamos una lista de python que contenga los nombres de las columnas
my_columns_names = ["temperature", "activity"]

# Creamos el DataFrame
my_dataframe = pd.DataFrame(data=my_data, columns=my_columns_names)

# Imprimimos el DataFrame entero
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


# Añadimos una nueva columna

In [18]:
# Creamos una nueva columna llamada "adjusted"
my_dataframe["adjusted"] = my_dataframe["activity"] + 2
my_dataframe["whathever"] = my_dataframe["adjusted"] / 2

print(my_dataframe)

   temperature  activity  adjusted  whathever
0            0         3         5        2.5
1           10         7         9        4.5
2           20         9        11        5.5
3           30        14        16        8.0
4           40        15        17        8.5


# Especificando un subset de datos

In [19]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), "\n")

print("Row #2:")
print(my_dataframe.iloc[[2]], "\n")

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], "\n")

print("Column \"temperature\":")
print(my_dataframe["temperature"])

Rows #0, #1, and #2:
   temperature  activity  adjusted  whathever
0            0         3         5        2.5
1           10         7         9        4.5
2           20         9        11        5.5 

Row #2:
   temperature  activity  adjusted  whathever
2           20         9        11        5.5 

Rows #1, #2, and #3:
   temperature  activity  adjusted  whathever
1           10         7         9        4.5
2           20         9        11        5.5
3           30        14        16        8.0 

Column "temperature":
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64


# Task 1


In [20]:
random_int = np.random.randint(low = 0, high = 101, size = (3,4))
print(random_int)

[[ 52  89  30  26]
 [ 42  37  72  47]
 [100  79  64  61]]


In [21]:
#random_numbers = np.random.randint(low=0, high=101, size=4)

#data_to_fill = np.array([random_numbers, random_numbers * 2, random_numbers * 3])
#print(data_to_fill)

In [22]:
my_col = ["Eleonor", "Chidi", "Tahani", "Jason"]

In [23]:
df = pd.DataFrame(data=random_int, columns=my_col)
print(df)

   Eleonor  Chidi  Tahani  Jason
0       52     89      30     26
1       42     37      72     47
2      100     79      64     61


In [24]:
df.Eleonor[1]

42

In [25]:
df["Janet"] = df["Tahani"] + df["Jason"]

In [26]:
df

Eleonor  Chidi  Tahani  Jason  Janet
0       52     89      30     26     56
1       42     37      72     47    119
2      100     79      64     61    125

# Copiando un DataFrame

  • **Referenciar:** Si asignas un data frame a una variable, cualquier cambio en el DataFrame o en la nueva variable afectará al otro.

  • **Copia:** Si llamamos al método "pd.DataFrame.copy", creamos una copia independiente real. Los cambios en el DataFrame original o en la caopia no afectaran el uno en el otro.

In [30]:
# Creamos una referencia asignando my_dataframe a una nueva variable
print("Experiment with a reference:")
reference_to_df = df

# Imprimir el valor inicial de una celda particular
print("   Starting value of df: %d" % df["Jason"][1])
print("   Starting value of reference_to_df: %d\n" % reference_to_df["Jason"][1])

# Modificamos una celda en "df"
df.at[1, "Jason"] = df["Jason"][1] + 5
print("   Updated df: %d\n\n" % reference_to_df["Jason"][1])

# Crear una copia real de my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Imprimir el valor inincial de una celda particular
print("   Starting value of my_dataframe: %d\n" % my_dataframe["activity"][1])
print("   Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe["activity"][1])

# Modificamos una celda en df
my_dataframe.at[1, "activity"] = my_dataframe["activity"][1] + 3
print("   Updated my_dataframe: %d" % my_dataframe["activity"][1])
print("   copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe["activity"][1])

Experiment with a reference:
   Starting value of df: 62
   Starting value of reference_to_df: 62

   Updated df: 67


Experiment with a true copy:
   Starting value of my_dataframe: 16

   Starting value of copy_of_my_dataframe: 16

   Updated my_dataframe: 19
   copy_of_my_dataframe does not get updated: 16
